texts = {1: 'Meow',
        2: 'Mrau',
        3: 'Mrrrr',
        4: 'What?!',
        5: 'Love is in the air',
        6: 'Balance between work and relax',
        7: 'Look!\nA flying mouse',
        8: 'Zzzzzzz',
        9: 'Studying cat science',
        10: 'Food???',
        11: 'Meh...',
        12: 'sCATeboard',
        13: 'Breakdance',
        14: 'Hmmmm',
        15: 'HA!',
        16: 'You came to the wrong neighbourhood',
        17: 'Zzzzzz',
        18: 'What a wonderful world',
        19: 'Shopping',
        20: 'Little Meow',
        21: 'O.O',
        22: 'He He HeHe',
        23: 'Floor is lava!',
        24: 'Merry christmas!'}